naam= (input("wat is je naam? ")).capitalize()
aderss= (input("wat is je aders? ")).capitalize()
postcode= (input("wat is je postcode? ")).capitalize()
woonplaats=(input("wat is je woonplaats? ")).capitalize()
print('-' * 37)
print(f'| Naam:          {naam}')
print(f'| Adress:        {aderss}')
print(f'| postcode:      {postcode}')
print(f'| woonplaats:    {woonplaats}')
print('-' * 37)